export default {
    PRODUCT_DATA_FROM_FILE: 'PRODUCT_DATA_FROM_FILE',
    GET_EDIT_PRODUCT_DATA: 'GET_EDIT_PRODUCT_DATA',
    UPDATE_PRODUCT_DATA: 'UPDATE_PRODUCT_DATA',
    SAVE_EDITED_DATA: 'SAVE_EDITED_DATA',
}